### ISSUE TITLE
Regaring Kid Dracula's incompatibility

### ISSUE THREAD

**Issue by redunka-zver** [farmerbb/RED-Project#1]
Hi! 
Perhaps this information could be useful for the Castlevania Anniversary Collection's page?
http://forums.nesdev.com/viewtopic.php?f=3&t=19677#p245961

English translation of Kid Dracula requires a special SRAM savefile that is generated on launch by the Collection's scripting engine.

It's possible to run it on other emulators by taking the SRAM data from the script (the path is "073\script\title_standalone.nut") and saving it as a .SAV file, which should be compatible with any emulator.

**Comment by farmerbb** [comment]
Thanks so much for bringing this to my attention!

Looks like there's an easy way to extract the SRAM data directly from title_standalone.nut using [Swiss File Knife](http://stahlworks.com/dev/swiss-file-knife.html) and this one-liner:

`./sfk filter /path/to/073/script/title_standalone.nut -skipfirst=107 -head=363 +hextobin kid-dracula.sav`

I'll get this added to the wiki page :)  Thanks again!

**Comment by Auster-South-Anemoi** [comment]
Hello. How does one use this .sav file once extracted?

**Comment by redunka-zver** [comment]
> 
> 
> Hello. How does one use this .sav file once extracted?

The .sav file should be placed in whichever directory your emulator uses for battery saves (not to be confused with savestates), the exact path may vary for different emulators, and the save's filename usually has to match rom's filename.

For standalone FCEUX the default path is  the "sav" folder next to the emulator's executable, for Nestopia UE it's "save", and both of these emulators also support custom path configurations.

If you're using RetroArch, then the save will go into "RetroArch/saves/", and you will also need to rename the savefile's extension from ".sav" to ".srm".

**Comment by Auster-South-Anemoi** [comment]
> FCEUX

Thanks for your reply. It helped a lot.
Only two or three emulators didn't work. I tried the process for the standalone Nestopia v1.49, and it didn't work. On FCEUX, it loads normally. And doing the process for Retroarch for PC, the cores FCEUmm, Mesen and QuickNES can also open it (and Emux NES and Nestopia UE can't).

**Comment by redunka-zver** [comment]
> 
> Thanks for your reply. It helped a lot.
> Only two or three emulators didn't work. I tried the process for the standalone Nestopia v1.49, and it didn't work. On FCEUX, it loads normally. And doing the process for Retroarch for PC, the cores FCEUmm, Mesen and QuickNES can also open it (and Emux NES and Nestopia UE can't).

Glad I could help. :)

Indeed, Nestopia UE has to rely on an xml database, that's why it may be a little tricky to use it for playing romhacks or games that didn't have an official cartridge release, but there's still a way to play them by converting the roms to NES 2.0 format (should also be compatible with any other modern emulator as well).

Standalone Nestopia UE should have a menu named "Edit iNES Header", just load the ROM in there, switch to "Extended iNES" tab and try setting sub mapper to a different number (between 0 and 15), the proper sub mapper specifically for this version of Kid Dracula is "2", if I recall correctly.
