### ISSUE TITLE
PSA: Data East Retro Classix will be removed from digital storefronts on April 29

### ISSUE THREAD

**Issue by RealRelativeEase** [farmerbb/RED-Project#157]
A dozen of arcade games developed by Data East have been re-released under the Retro Classix banner on digital storefronts such as Steam and GOG. Apparently, the licensing deal with the publisher has run out and the games will be delisted on April 29. As of now, the following games are still available for purchase:

- Night Slashers
- Bad Dudes vs. Dragon Ninja
- BreakThru
- Express Raider
- Gate of Doom
- Heavy Barrel
- Joe & Mac - Caveman Ninja
- Joe & Mac Returns
- SRD - Super Real Darwin
- Super Burger Time
- Two Crude
- Wizard Fire

The emulation on these Retro Classix releases is notoriously bad, but the installation folders include .zip folders of the respective games which you can use with an emulator of your choice. The games are currently on sale, so if you're interested in any of these, you'll have to get them before they're delisted.

**Comment by kjetil-f** [comment]
Thanks for the heads up.
