### ISSUE TITLE
Irem Arcade Hits - some games fail to run with fbneo after extraction

### ISSUE THREAD

**Issue by has207** [farmerbb/RED-Project#159]
I'm not sure if it's an issue with the version of FinalBurn Neo or the extraction script, but there seems to be a mismatch with a handful of the Irem games that are extracted using the gist linked in the wiki. Specifically the issue I see trying to run them with fbneo64.exe v1.0.0.03:

Air Duel
--------
The following ROMs are invalid:
  ? essential program ROM ad_c-h0-c.ic40 was not found.
  ? essential program ROM ad_c-l0-c.ic37 was not found.
  ? program ROM ad_c-pr-c.ic1 was not found.

Battle Chopper
---------------
 ? program ROM mh_c-pr-b.ic1 was not found.

Image Fight
------------
? program ROM if_c-pr-a.ic1 was not found.

Kung-Fu Master (game starts despite the error)
-----------------
The following ROMs are invalid:
  ? graphics ROM b-6f-.bin has a CRC of 0D968558 (correct is 82C20D12).

Legend of Hero Tonma
-----------------------
  ? program ROM tom_c-pr-b.ic1 was not found.

Vigilante (game starts despite the error)
---------
  ? graphics ROM p09_16l8.bin was not found.
  ? graphics ROM m05_16l8.bin was not found.
  ? graphics ROM b01_16l8.bin was not found.

Is there a specific version of fbneo that should be used or is it an issue with the extraction process? I bought the game on Mac store and extracted on OSX.

**Comment by stuckinstyx** [comment]
Here is what I found for the games you list: (I use Launchbox as a frontend to Retroarch)

Air Duel: Can't get it to work
Battle Chopper: Works with Mame2010
Image Fight: Works with Mame2010
Kung-Fu Master: Works with Mame2010
Legend of Hero Tonma: Works with Mame2010
Vigilante: Can't get it to work

**Comment by has207** [comment]
Okay I did some testing with various mame versions, it looks like mame 0.170 runs all these roms, though there are warnings about missing bins or wrong crc on the ones that I listed originally. But they all boot and run with that version of mame, and some later ones too but with more warnings, so I think 0.170 is maybe best one to run them.

**Comment by has207** [comment]
I updated the gist mention mame 0.170 so going to close this as I'm not sure anybody is actually going to do work on trying to create the dumps in a way that's compatible with latest version of either mame or fbneo
