### ISSUE TITLE
Mega Man Legacy Collection

### ISSUE THREAD

**Issue by iGom** [farmerbb/RED-Project#16]
I can confirm that I was able to extract all 12 roms from current MMLC Proteus.exe `CRC32: E70E4AA2` using this python script, and all roms matched no-intro database and are playable in emulators 
https://gist.github.com/VideogameScrapbook/e1dc851234b0bdba97b0c73cf9f52aed

additionally, it also provides the password to extract data.pie:
`P091uWEdwe4lI6StDNMNlkodPGvJ38bL3HW6t3BCMYdFi83FXKu7k0NsHP8caDKS`

![obraz](https://user-images.githubusercontent.com/4786772/111864708-781a8d00-895a-11eb-824f-e059e156d008.png)

**Comment by tydog98** [comment]
I've made a wiki entry for this, if you would like to close the issue.
