### ISSUE TITLE
Source folders are empty

### ISSUE THREAD

**Issue by MichaelMacha** [farmerbb/RED-Project#20]
They contain the README, but no other code. I'm not actually sure whether this is an open project or not—it *feels* open— but this is a little misleading and it would be great if you could fix it or remove them.

Thanks.

**Comment by einstein95** [comment]
The files in the repo contain the hashes for roms extracted from some games. The main information hosted in this repo is in the wiki.

**Comment by farmerbb** [comment]
einstein95 is correct.  I've updated the readme to (hopefully) make the wiki link more prominent.
