### ISSUE TITLE
Zombies Ate My Neighbors / Ghoul Patrol Info.

### ISSUE THREAD

**Issue by Computerlabrat** [farmerbb/RED-Project#32]
There's a Steam thread about how to get the files from the Steam and GOG versions of the two pack. In case you want to add it, here: https://steamcommunity.com/app/1137970/discussions/0/3046105389665628847/

**Comment by Retro64** [comment]
These two worked for me on GOG-Version
```
dd bs=1 skip=26867136 count=1048576 if=ZAMN_GP.exe of=gp.sfc status=progress
dd bs=1 skip=28346700 count=1048576 if=ZAMN_GP.exe of=zamn.sfc status=progress
```

**Comment by Computerlabrat** [comment]
Just curious, is there any windows counterpart command for these or should I get something like Cygwin or the Linux Subsystem?

**Comment by einstein95** [comment]
> Just curious, is there any windows counterpart command for these or should I get something like Cygwin or the Linux Subsystem?

Open ZAMN_GB.EXE in a hex editor, go to the offset specified by `skip=` (note that it's in decimal, not hex), select 1048576 bytes from that offset and save it as the sfc name

**Comment by Computerlabrat** [comment]
Yeah, I know about the hex editor thing. I'm just wondering if there's a command line option for windows is all.
