### ISSUE TITLE
Collection of SaGa/Final Fantasy Legend

### ISSUE THREAD

**Issue by Computerlabrat** [farmerbb/RED-Project#39]
Open Steam in Desktop mode

Find Collection of SaGa Final Fantasy from your games.

Your file browser should open to somewhere along the lines of Steam\Steamapps\common\Sa・Ga COLLECTION. Navigate through the folders to get to Sa・Ga COLLECTION_Data\StreamingAssets\aa\Windows\StandaloneWindows64. This might be different based on your operating system.

The naming scheme can be determined by looking the first 7 characters of the file names, but just to make sure it's all here:

Final Fantasy Legend 1 is in romffl1_assets_all_e8aea7590909c1eb45f3809e4f3da68f.bundle
Final Fantasy Legend 2 is in romffl2_assets_all_5d8137a1fdbca63a9fa7b533aa1d9db0.bundle
Final Fantasy Legend 3 is in romffl3_assets_all_5818995041c2c3cbe070bb00b1783274.bundle
SaGa 1 is in romjsg1_assets_all_c6047cf2db4f38cbc8f51d592e1a1c76.bundle
SaGa 2 is in romjsg2_assets_all_148d5b61843deae44f69f2dfcc30e168.bundle
SaGa 3 is in romjsg3_assets_all_942cc896cee03850dc45bfc837017e8f.bundle

You can load the files in Unity Asset Studio. I got it from [here.](https://github.com/Perfare/AssetStudio/releases )
I used Asset Studio v0.16.40 (which is the latest version at the time of writing this) for dotnet472, but if you have a different dotnet framework version, you might want to select a different version to match

As a precaution, I'd suggest scanning software you get from the net with anti-virus software before installing/running it. When you've done that and if you you're comfortable running it, extract the program and run Asset Studio GUI.exe.

If you get a message about the software being blocked, right click Asset Studio GUI.exe, click properties, then click the check box about unblocking it and try again.

Next, click file, then load file, then find the file from the list you want and then click open.

Once you open the file you want, click on Asset List.

Right click on the game file. These files are:

FFL1 for Final Fantasy Legend 1
FFL2 for Final Fantasy Legend 2
FFL3 for Final Fantasy Legend 3
JSG1 for SaGa 1
JSG2 for SaGa 2
JSG3 for SaGa 3

If you have trouble finding them, you can click on where it says name or container above the file list to sort them in a way to make them easier to find, then right click the file you're wanting.

Click export selected assets.

Select where you want the game to be.

Go to the folder you exported the game to and then enter the TextAsset folder.

Inside should be a file you exported, but it is advised you change the file extension from .bytes to something Game Boy related such as .gb.

**Comment by tydog98** [comment]
A wiki page has been added for this using the game-extraction-toolbox scripts, if you would like to close this issue.
